### PR TITLE
OBJ-210 Clone map passed to structured logging to stop duplicate message

### PR DESCRIPTION
**Pull request by mwestacott**
This will result in correct messages in the TEST and LIVE logs, e.g.

```
{"created":"2020-10-21T14:03:14.555Z","event":"info","namespace":"strike-off-objections-api","context":"PNHxpd7o4hnhw_O3FCgFMR7uIJG2","data":{"message":"GET /{objectionId} request received","company_number":"05916434","objection_id":"5f903f9e938cb425e88c81f0"}}
{"created":"2020-10-21T14:03:14.602Z","event":"info","namespace":"strike-off-objections-api","context":"PNHxpd7o4hnhw_O3FCgFMR7uIJG2","data":{"message":"Finished GET /{objectionId} request","company_number":"05916434","objection_id":"5f903f9e938cb425e88c81f0"}}
```

As opposed to output with duplicate messages:

```
{"created":"2020-10-21T14:03:14.555Z","event":"info","namespace":"strike-off-objections-api","context":"PNHxpd7o4hnhw_O3FCgFMR7uIJG2","data":{"message":"GET /{objectionId} request received","company_number":"05916434","objection_id":"5f903f9e938cb425e88c81f0"}}
{"created":"2020-10-21T14:03:14.602Z","event":"info","namespace":"strike-off-objections-api","context":"PNHxpd7o4hnhw_O3FCgFMR7uIJG2","data":{"message":"GET /{objectionId} request received","company_number":"05916434","objection_id":"5f903f9e938cb425e88c81f0"}}
```

### CODE REVIEW

**Review by ICoxCH — APPROVED** [review]
Sonar is not happy about your unit tests being public, but happy enough with your implementation

**Review by mattch1 — APPROVED** [review]

**Comment by mwestacott** [comment]
> Sonar is not happy about your unit tests being public, but happy enough with your implementation

Oh yes. Will make private.

**Comment by ICoxCH** [comment]
> > Sonar is not happy about your unit tests being public, but happy enough with your implementation
> 
> Oh yes. Will make private.

I think no access modifier will be enough, that's what the rest of our tests are

**Review by markpit — APPROVED** [review]

**Comment by markpit** [comment]
4 smells

**Review by sroberts2 — APPROVED** [review]

**Review by ICoxCH — APPROVED** [review]

**Pull request merged**
